config/routes.rb
Rails.application.routes.draw do
  root 'teams#new'

  resources :teams, only: [:new, :create, :destroy] do
  	collection do
  		post 'join'
  	end
  	resources :users, only: [:new, :create, :edit, :update, :index] do
      member do
        patch 'deactivate'
        patch 'activate'
      end
    end
    resources :channels, only: [:new, :create, :index, :destroy] do
      member do
        patch 'join'
        patch 'reject'
        delete 'unsubscribe'
      end
    end
    resource :team_founder, only: [:new, :create, :edit, :update]
  end

  get 'msgs/:type/:id/:filter', to: 'msgs#index'
  post 'msgs', to: 'msgs#create'
  delete 'msgs/:id', to: 'msgs#destroy'

  resources :invitations, only: [:new, :create]

  post 'login', to: 'sessions#create'
  get 'login', to: 'sessions#new'
  delete 'logout', to: 'sessions#destroy'

  get 'password_reset', to: 'password_reset#new'
  post 'password_reset', to: 'password_reset#create'
  get 'password_reset/:password_reset_token', to: 'password_reset#edit', as: 'edit_password_reset'
  patch 'password_reset/:password_reset_token', to: 'password_reset#update', as: 'update_password_reset'

end

app/views/notifier/password_reset.html.erb
<h2>Reset your password</h2>

<p>You can reset your password here: <%= link_to edit_password_reset_url(@user.password_reset_token, host: 'localhost:3000'), edit_password_reset_url(@user.password_reset_token, host: 'localhost:3000') %></p>

<p>Kind regards,</p>
<p>The MySlack team</p>

app/views/notifier/password_reset.txt.erb
Reset your password:
You can reset your password here: <%= edit_password_reset_url(@user.password_reset_token, host: 'localhost:3000') %>
Kind regards,
The MySlack team

app/views/notifier/send_activate_request.html.erb
<h2><%= @user.name %> has send you a request to activate his/her account.</h2>
<p>You can activate the account in your team management panel. Just log in to your account: <%= link_to login_url(host: 'localhost:3000'), login_url(host: 'localhost:3000') %></p>
<p>Ignore this message if you do not want to activate the account or the message is invalid.</p>
<p>Kind regards,</p>
<p>The MySlack team</p>

app/views/notifier/send_activate_request.txt.erb
<%= @user.name %> has send you a request to activate his/her account.
You can activate the account in your team management panel. Just log in to your account.
Ignore this message if you do not want to activate the account or the message is invalid.
Kind regards,
The MySlack team

app/views/notifier/send_activate_response.html.erb
<h2><%= @user.name %>, your account is active again.</h2>
<p>Just log in to your account: <%= link_to login_url(host: 'localhost:3000'), login_url(host: 'localhost:3000') %></p>
<p>Enjoy.</p>
<p>Kind regards,</p>
<p>The MySlack team</p>

app/views/notifier/send_activate_response.txt.erb
<%= @user.name %>, your account is active again.
Just log in to your account: <%= login_url(host: 'localhost:3000') %>
Enjoy.
Kind regards,
The MySlack team

app/views/notifier/welcome.html.erb
<h2>Welcome to the MySlack communicator <%= @user.name %>.</h2>
<p>We appreciate that you have choosed MySlack for working with your team.</p>
<p>We wish you and your team a perfect collaboration</p>
<p>Kind regards,</p>
<p>The MySlack team</p>

app/views/notifier/welcome.txt.erb
Welcome to the MySlack communicator <%= @user.name %>.
We appreciate that you have choosed MySlack for working with your team.
We wish you and your team a perfect collaboration
Kind regards,
The MySlack team