config/routes.rb
Rails.application.routes.draw do
  root 'teams#new'

  resources :teams, only: [:new, :create, :destroy] do
  	collection do
  		post 'join'
  	end
  	resources :users, only: [:new, :create, :edit, :update, :index] do
      member do
        patch 'deactivate'
        patch 'activate'
      end
    end
    resources :channels, only: [:new, :create, :index, :destroy] do
      member do
        patch 'join'
        patch 'reject'
        delete 'unsubscribe'
      end
    end
    resource :team_founder, only: [:new, :create, :edit, :update]
  end

  get 'msgs/:type/:id/:filter', to: 'msgs#index'
  post 'msgs', to: 'msgs#create'
  delete 'msgs/:id', to: 'msgs#destroy'

  resources :invitations, only: [:new, :create]

  post 'login', to: 'sessions#create'
  get 'login', to: 'sessions#new'
  delete 'logout', to: 'sessions#destroy'

  get 'password_reset', to: 'password_reset#new'
  post 'password_reset', to: 'password_reset#create'
  get 'password_reset/:password_reset_token', to: 'password_reset#edit', as: 'edit_password_reset'
  patch 'password_reset/:password_reset_token', to: 'password_reset#update', as: 'update_password_reset'

end

app/models/msg.rb
class Msg < ActiveRecord::Base

#Associations	
	belongs_to :sender, class_name: "User", foreign_key: "sender_id"
	belongs_to :recipient, polymorphic: true

#Validations
	validates :sender_id, presence: true
	validates :recipient_id, presence: {message: "Please enter the recipient of the message."}
	validates :recipient_type, presence: {message: "Please enter the type of recipient."}
	validates :content, presence: {message: "You are trying to send a message without any content."},
											length: {maximum: 2000, message: "Your message is too long."}
	validate :addressed_properly?, if: "recipient_id.present? && recipient_type.present?"

	def addressed_properly?
		case recipient_type
		when "Channel"
			if !(User.find(sender_id).channels.ids.include?(recipient_id))
				errors.add(:recipient_id, "No such channel belongs to your team.")
			end
		when "User"
			if !(User.find(sender_id).team_members.ids.include?(recipient_id))
				errors.add(:recipient_id, "There is no such user in your team.")
			end
		else
			errors.add(:recipient_type, "There is no such recipient type.")
		end
	end

#Query Scope
	scope :in_channels, ->(channel_array) { where(recipient_type: "Channel", recipient_id: channel_array)}
	scope :between_team_members, ->(first_member, second_member) { where(recipient_type: "User", recipient_id: [first_member, second_member], sender_id: [first_member, second_member]) }

	scope :today, -> { where(created_at: Date.today.midnight..Time.now) }
	scope :yesterday, -> { where(created_at: Date.yesterday.midnight..Date.today.midnight)}
	scope :this_week, -> { where(created_at: Date.today.beginning_of_week.midnight..Time.now)}
	scope :last_week, -> { where(created_at: Date.today.prev_week.midnight..Date.today.beginning_of_week.midnight)}
	scope :during_year, ->(year) { where(created_at: Date.new(year.to_i).all_year) }
	scope :during_month, ->(month) { where(created_at: parse_month(month)) }

	scope :with_text, ->(text) { where("content LIKE ?", "%#{text}%") }

#Private methods
	private
	def self.parse_month(month)
		if Date.strptime(month, "%m") <= Date.today
			Date.strptime(month, "%m").all_month
		else
			Date.strptime(month, "%m").prev_year.all_month
		end
	end

#Public methods & Overrides
	public
	def send_time
		created_at.to_formatted_s(:short)
	end

	def as_json(options={})
		options[:only] = [:id, :content]
		options[:methods] = :send_time
		options[:include] = { sender: { only: :name } }
		super(options)
	end

end

app/controllers/msgs_controller.rb
class MsgsController < ApplicationController
	before_action :require_user
	before_action :find_user
	before_action :find_current_user_team
	before_action :provide_message_template, only: [:index]

	def index
		if params[:type] == 'channel'&& find_channel
			msgs_in_channel = Msg.in_channels(@channel)
			@msgs = find_messages(msgs_in_channel)
			respond_to_index_request
		elsif params[:type] == 'user' && find_team_member
			msgs_between_team_members = Msg.between_team_members(current_user, @team_member)
			@msgs = find_messages(msgs_between_team_members)
			respond_to_index_request
		else
			render file: 'public/404', status: :not_found
		end
	end

	def create
		@msg = current_user.sent_msgs.new(msg_params)
		respond_to do |format|
			if @msg.save
				if request.xhr?
					format.json { render json: @msg }
				else
					format.html { redirect_to "/msgs/#{params[:msg][:recipient_type].downcase}/#{params[:msg][:recipient_id]}/all" }
				end
			else
				flash[:alert] = "The message was not sent"
				format.html { redirect_to "/msgs/channel/#{current_user.team.channels.first.id}/all" }
			end
		end
	end

	def destroy
		@msg = current_user.sent_msgs.find_by(id: params[:id])
		if @msg.destroy
			redirect_to "/msgs/#{@msg.recipient_type.to_s.downcase}/#{@msg.recipient_id}/all"
		else
			flash[:alert] = "The message was not destroyed"
			redirect_to "/msgs/#{@msg.recipient_type.to_s.downcase}/#{@msg.recipient_id}/all"	
		end
	end

	private

	def msg_params
		params.require(:msg).permit(:content, :recipient_type, :recipient_id)
	end

	def find_user
		@user = current_user
	end

	def find_channel
		@channel = current_user.channels.find_by(id: params[:id])
	end

	def find_team_member
		@team_member = current_user.team.users.find_by(id: params[:id])
	end

	def provide_message_template
		@msg = Msg.new
	end

	def filter_messages(msgs, search_text, filter, date=nil)
		searched_msgs = msgs.with_text(search_text)
		case filter
		when 'today'
			searched_msgs.today
		when 'yesterday'
			searched_msgs.yesterday
		when 'this_week'
			searched_msgs.this_week
		when 'last_week'
			searched_msgs.last_week
		when 'during_year'
			searched_msgs.during_year(date)
		when 'during_month'
			searched_msgs.during_month(date)
		else
			searched_msgs
		end
	end

	def find_messages(msgs)
		filter_messages(msgs, params[:q], params[:filter], params[:date]).order(:created_at)
	end

	def respond_to_index_request
		respond_to do |format|
			if request.xhr?
				format.html { render partial: 'msgs_content' }
				format.json { render json: @msgs }
			else
				format.html { render layout: 'msgs_panel' }
			end
		end
	end
	
end

app/helpers/msgs_helper.rb
module MsgsHelper

	def invitation_content(invitation)
		invitation.content.gsub(/#\d+ [A-Z][a-z]+/, '')
	end

	def parse_invitation(invitation)
		invitation.content.match(/#\d+ [A-Z][a-z]+/).to_s.delete('#').split(" ")
	end

	def join_channel_link(invitation)
		template_info = parse_invitation(invitation)
		html = "#{invitation.sender.name} is inviting you to join the <strong>#{template_info[1]}</strong> channel. Would you like to join?"
		html += link_to " Yes, sure. |", "/teams/#{invitation.sender.team_id}/channels/#{template_info[0].to_i}/join", method: :patch
		html += link_to " No, thanks.", "/teams/#{invitation.sender.team_id}/channels/#{template_info[0].to_i}/reject", method: :patch
		return html.html_safe
	end

	#helpers for the filter menu

	def filter_months
		months_tag = capture {""}
		date = Date.new(1)
		1.upto(12) do
			query_string = {date: date.month}.to_query
			months_tag += capture do
				content_tag :li do
					link_to "#{date.strftime('%B')}", "during_month?#{query_string}", remote: true
				end 
			end
			date = date.next_month
		end
		months_tag
	end

	def filter_years
		years_tag = capture {""}
		year = Time.now.year
		5.times do
			query_string = {date: year}.to_query
			years_tag += capture do
				content_tag :li do
					link_to "#{year}", "during_year?#{query_string}", remote: true
				end 
			end
			year -= 1
		end
		years_tag
	end

end

app/views/msgs/_filter_menu.html.erb
<li><%= link_to 'All', "all", remote: true %></li>
<li><%= link_to 'Today', "today", remote: true %></li>
<li><%= link_to 'Yesterday', "yesterday", remote: true %></li>
<li><%= link_to 'This Week', "this_week", remote: true %></li>
<li><%= link_to 'Last Week', "last_week", remote: true %></li>
<li>
	<%= link_to 'During Month', '' %>
	<ul class="menu">
		<%= filter_months %>
	</ul>
</li>
<li><%= link_to 'During Year', '' %>
	<ul class="menu">
		<%= filter_years %>
	</ul>
</li>

app/views/msgs/_message_console.html.erb
<div class="message-console">
<%= form_for @msg, remote: true do |f| %>
<div class="input-group">
	<%= f.text_field :content, class: "input-group-field" %>
	<%= f.hidden_field :recipient_type, value: (recipient.class.to_s == 'Channel' ? 'Channel' : 'User') %>
	<%= f.hidden_field :recipient_id, value: recipient.id %>
	</fieldset>
	<div class="input-group-button">
		<%= f.submit 'Send', class: "message-button button" %>
	</div>
</div>
<% end %>
<div>

app/views/msgs/_msgs_content.html.erb
<% unless @msgs.nil? %>
<div class="no-bullet message-content">
	<% @msgs.each do |msg| %>
		<% if msg.is_a? Invitation %>
			<div class="message">
			<% if msg.sender == @user %>
				<%= link_to "/msgs/#{msg.id}", method: :delete do %>
					<span class="delete-message-button">&#10006;</span>
				<% end %>
				<% if msg.state == 'pending' %>
					<%= msg.send_time %>| <strong>You have sent an invitation to <%= msg.recipient.name %>.</strong>
				<% elsif msg.state == 'accepted' %>
					<%= msg.send_time %>| <strong><%= msg.recipient.name %> accepted your invitation.</strong>
				<% else %>
					<%= msg.send_time %>| <strong><%= msg.recipient.name %> rejected your invitation.</strong>
				<% end %>
			<% else %>
				<% if msg.state == 'pending' %>
				<p><%=msg.send_time%> |<strong> Invitation from <%=msg.sender.name%>:</strong></p>
					<p><em><%= invitation_content(msg) %></em></p>
					<%= join_channel_link(msg) %>
				<% elsif msg.state == 'accepted' %>
					<p><%=msg.send_time%> |<strong> Invitation from <%=msg.sender.name%>:</strong></p>
					<p><em><%= invitation_content(msg) %></em></p>
					You have accepted the invitation.
				<% else %>
					<p><%=msg.send_time%> |<strong> Invitation from <%=msg.sender.name%>:</strong></p>
					<p><em><%= invitation_content(msg) %></em></p>
					You have rejected the invitation.
				<% end %>
			<% end %>	
			</div>
		<% else %>
			<div class="message">
			<% if msg.sender == @user %>
				<%= link_to "/msgs/#{msg.id}", method: :delete do %>
					<span class="delete-message-button">&#10006;</span>
				<% end %>
			<% end %>
			<%= msg.send_time %>| <strong><%=msg.sender.name%>:</strong> 
			<span class="message-text"><%= msg.content %></span>
			</div>
		<% end %>
	<% end %>
</div>
<% end %>

app/views/msgs/_search_form.html.erb
<%= form_tag({}, method: "get", remote: true, id: 'search-form') do %>
	<%= text_field_tag :q, nil, placeholder: 'Search' %>
<% end %>

app/views/msgs/_team_menu.html.erb
<ul class="recipient-groups menu vertical">
	<li class="team-name menu-text"><%= @team.name %></li>
	<li class="menu-text">List of Channels:</li>
	<li><%= link_to 'Create a Channel +', new_team_channel_path(@team) %></li>
	<%= recipient_groups(@user.channels, @user) %>
	<li class="menu-text">List of Team Members:</li>
	<li><%= link_to 'Send Invitation +', new_invitation_path %></li>
	<%= recipient_groups(@user.team_members, @user) %>
</ul>
<div class="row settings-menu">
	<% if @user.is_a? TeamFounder %>
		<div class="small-4 columns">
			<%= link_to edit_team_team_founder_path(@team) do %>
				<i class="fi-torso icon-large"></i>
			<% end %>
		</div>
		<div class="small-4 columns">
		<%= link_to team_users_path(@team) do %>
			<i class="fi-torsos-all icon-large"></i>
		<% end %>
		</div>
	<% else %> 
		<div class="small-4 columns">
			<%= link_to edit_team_user_path(@team, @user) do %>
				<i class="fi-torso icon-large"></i>
			<% end %>
		</div>
	<% end %>
	<div class="small-4 end columns">
		<%= link_to team_channels_path(@team) do %>
			<i class="fi-volume icon-large"></i>
		<% end %>
	</div>
</div>

app/views/msgs/index.html.erb
<div class="message-container">
	<%= render 'msgs_content' %>
</div>